name: "Build & Test"

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      # - '.github'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      # - '.github'

env:
  pnpm_version: 8

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [18, 20]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: ${{ env.pnpm_version }}
      - run: pnpm install
      - run: pnpm all
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          name: ${{ matrix.os }}/${{ matrix.node-version }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}